### ISSUE TITLE
Support for MC 1.21.3

### ISSUE THREAD

**Issue by Loapu** [myth-MC/social#10]
PaperMC [recently released](https://forums.papermc.io/threads/1-21-3.1430/) a stable version for Paper 1.21.3, and I think it would make sense to now work on updating the plugin to support this version.

**Comment by U8092** [comment]
Thanks for taking the time to open this issue, Loapu!
I'm marking it with the wontfix label since everything seems to work fine in the latest development build (branch dev/0.2.x, public builds coming out soon). I won't be closing it until it is released, though.

Just for the record, a user recently reported in our Discord an issue that affects specific set-ups and prevents the plug-in from starting. This seemed an issue with PaperMC 1.21.3 at first but it is actually unrelated, and was fixed in commit [947f8a1](https://github.com/myth-MC/social/commit/947f8a1954d524c4e28180e2907cb442e0255be4#diff-9fdb5314741756ca0f7cdf95569bd0dc7da7a4742ad9715545cbce8d7851f33b).
